apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-endpoint-deployment
  labels:
    app: user-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-endpoint
  template:
    metadata:
      name: user-endpoint
      labels:
        app: user-endpoint
    spec:
      containers:
        - name: service-user-v1
          image: ollidevs/service-users:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8004
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_HOST
            - name: PORT
              value: "8004"
            - name: SERVICE_NAME
              value: "user"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_PORT
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: house-bank-secrets
                  key: POSTGRES_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: user-endpoint-service # Sets service name
  labels:
    app: user-endpoint # Labels and Selectors
spec:
  type: NodePort
  ports:
      - protocol: TCP
        port: 8004
        targetPort: 8004
  selector:
    app: user-endpoint