apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-endpoint-deployment
  labels:
    app: transaction-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-endpoint
  template:
    metadata:
      name: transaction-endpoint
      labels:
        app: transaction-endpoint
    spec:
      containers:
        - name: service-transaction-v1
          image: ollidevs/service-transactions:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8003
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_HOST
            - name: PORT
              value: "8003"
            - name: SERVICE_NAME
              value: "transaction"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_PORT
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: house-bank-secrets
                  key: POSTGRES_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-endpoint-service # Sets service name
  labels:
    app: transaction-endpoint # Labels and Selectors
spec:
  type: NodePort
  ports:
      - protocol: TCP
        port: 8003
        targetPort: 8003
  selector:
    app: transaction-endpoint