apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-endpoint-deployment
  labels:
    app: property-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-endpoint
  template:
    metadata:
      name: property-endpoint
      labels:
        app: property-endpoint
    spec:
      containers:
        - name: service-property-v1
          image: ollidevs/service-property:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8002
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_HOST
            - name: PORT
              value: "8002"
            - name: SERVICE_NAME
              value: "property"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: house-bank-config
                  key: DB_PORT
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: house-bank-secrets
                  key: POSTGRES_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: property-endpoint-service # Sets service name
  labels:
    app: property-endpoint # Labels and Selectors
spec:
  type: NodePort
  ports:
      - protocol: TCP
        port: 8002
        targetPort: 8002
  selector:
    app: property-endpoint