services:
  # A Docker web service
  - type: web
    name: service-users
    env: docker
    repo: https://github.com/house-bank-ng/service-users.git # optional
    region: frankfurt # optional (defaults to oregon)
    branch: develop # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /v1/health
    envVars:
      - key: PORT
        value: 8002
      - key: VERSION
        value: 0.0.1
      - key: SERVICE_NAME
        value: user
      - fromGroup: db-vars-for-all